server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: false
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: ACCOUNT-API
          uri: lb://ACCOUNT-API
          predicates:
            - Path=/accounts/v1.0/**
      discovery:
        locator:
          enabled: true




management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE