version: '3.9'

services:

  transaction-api:
    image: transactionapp
    build:
      context: ./
      dockerfile: dockerfile

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s
    ports:
       #- 9060-9070:7072
        - 7076:7076
    volumes:
      - /data/compose-app
    #networks:
      #- boanetwork   
    

### put all the networks here
#networks:
  #boanetwork:
networks:
  default:
    external:
      name: siemensnetwork

  